In [1]:
import requests
from bs4 import BeautifulSoup
import random
import pandas as pd

In [2]:
title = "Data Science"
location = 'Toronto'

In [53]:
list_url = "https://www.linkedin.com/jobs-guest/jobs/api/seeMoreJobPostings/search?keywords=Data%2BScience&location=Toronto&geoId=100761630&distance=25&f_TPR=&f_E=1&start=0"
response = requests.get(list_url)

list_data = response.text
list_soup = BeautifulSoup(list_data, 'html.parser')
page_jobs = list_soup.find_all('li')

In [54]:
id_list = []
for job in page_jobs:
    base_card_div = job.find('div', {'class': 'base-card'})
    job_id = base_card_div.get('data-entity-urn').split(':')[3]
    id_list.append(job_id)
    print(job_id)

4157845565
4158928976
4151697992
4119528432
4152020457
4119525609
4148824726
4142865462
4137836889
4152269714

In [55]:
job_list = []
for job_id in id_list:
    job_post = {}
    job_url = f"https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/{job_id}"
    job_response = requests.get(job_url)
    print(job_response.status_code)
    job_soup = BeautifulSoup(job_response.text, 'html.parser')
    job_post['job_id'] = job_id
    try:
        job_post['job_title'] = job_soup.find('h2', {'class': 'top-card-layout__title font-sans text-lg papabear:text-xl font-bold leading-open text-color-text mb-0 topcard__title'}).text.strip()
    except:
        job_post['job_title'] = None

    try:
        job_post['company_name'] = job_soup.find('a', {'class': 'topcard__org-name-link topcard__flavor--black-link'}).text.strip()
    except:
        job_post['company_name'] = None

    try:
        job_post['time_posted'] = job_soup.find('span', {'class': 'posted-time-ago__text posted-time-ago__text--new topcard__flavor--metadata'}).text.strip()
    except AttributeError:
        try:
            job_post['time_posted'] = job_soup.find('span', {'class': 'posted-time-ago__text topcard__flavor--metadata'}).text.strip()
        except:
            job_post['time_posted'] = None

    try:
        job_post['num_applicants'] = job_soup.find('figcaption', {'class': 'num-applicants__caption'}).text.strip()
    except AttributeError:
        try:
            job_post['num_applicants'] = job_soup.find('span', {'class': 'num-applicants__caption topcard__flavor--metadata topcard__flavor--bullet'}).text.strip()
        except:
            job_post['num_applicants'] = None    
        
    job_list.append(job_post)

200
200
200
200
200
200
200
200
200
200

In [56]:
jobs_df = pd.DataFrame(job_list)
jobs_df

,job_id,job_title,company_name,time_posted,num_applicants
0,4157845565,Data Science Intern,Medcan,1 day ago,Over 200 applicants
1,4158928976,Junior Front End Developer,Diaryz,9 hours ago,Over 200 applicants
2,4151697992,Data Analyst Intern (Master's Degree),Stripe,5 days ago,Over 200 applicants
3,4119528432,Machine Learning - Master's level Internship,Vosyn,1 month ago,184 applicants
4,4152020457,"Associate Consulting Data Scientist, Summer 2025",Klick,6 days ago,Over 200 applicants
5,4119525609,Data Analytics and Visualisation - Master's Le...,Vosyn,1 month ago,Over 200 applicants
6,4148824726,RESEARCH TRAINEE,City of Toronto,1 week ago,Over 200 applicants
7,4142865462,Data Analyst Intern,Compugen Inc,2 weeks ago,Over 200 applicants
8,4137836889,Performance Analytics Intern,BMW Group Financial Services Canada,2 weeks ago,Over 200 applicants
9,4152269714,"Internship, Consumer Insights",Keurig Dr Pepper Canada,5 days ago,Over 200 applicants