In [60]:
import requests
import time
from bs4 import BeautifulSoup
import random
import pandas as pd

In [2]:
title = "Data Science"
location = 'Toronto'

In [77]:
start = 0
id_list = []

while True:
    list_url = f"https://www.linkedin.com/jobs-guest/jobs/api/seeMoreJobPostings/search?keywords=Data%2BScience&location=Toronto&geoId=100761630&distance=25&f_TPR=&f_E=1&start={start}"
    response = requests.get(list_url)
    print(response.status_code)
    print('Start Page: ' + str(start))

    if response.status_code != 200:
        break

    list_data = response.text
    list_soup = BeautifulSoup(list_data, 'html.parser')
    page_jobs = list_soup.find_all('li')
    
    count = 0
    for job in page_jobs:
        try:
            base_card_div = job.find('div', {'class': 'base-card'})
            job_id = base_card_div.get('data-entity-urn').split(':')[3]
            count += 1
        except:
            job_id = None
        
        id_list.append(job_id)
        print(job_id)

    if count == 0:
        print('no more jobs found, breaking...')
        break
    
    start += 10

    delay = random.uniform(1, 3)
    time.sleep(delay)

200
Start Page: 0
4157845565
4158928976
4119528432
4151697992
4152020457
4147951320
4148824726
4119525609
4142865462
4137836889
200
Start Page: 10
4119529288
4133929748
4125051373
4152269714
4133932050
3865661019
4044619966
4119531239
4142863604
4151657163
200
Start Page: 20
4153197222
4140332315
4034685159
4137838634
4127553466
4140796161
4142863599
4119528425
4148444657
4143839617
200
Start Page: 30
4158694556
4137841208
4144305570
4074138783
4151699925
4023651399
4142278426
4140182620
4079681490
4126022163
200
Start Page: 40
4079681490
4126022163
4144302955
4130716949
4150861635
4119524654
4143623069
4143616722
4119961097
4152501310
200
Start Page: 50
4128603621
4155473587
4144304342
4028289817
4028288972
4150627422
4144304545
4139613000
4117858826
4151664025
200
Start Page: 60
4139613000
4117858826
4151664025
4159855704
4159210429
4129222966
4135545584
4132562719
4115292600
4142546860
200
Start Page: 70
4089817006
4144305561
None
4144305370
4111741685
3959797316
4140182834
4121506125
4144303800
4156204537
200
Start Page: 80
4144303800
4156204537
4128419002
4145140352
4139521323
4139723185
4150697614
4144303735
4118391855
4131835721
200
Start Page: 90
4104817260
4159842193
4156854963
4053481308
4137762677
4149166948
4106268951
4124998190
4122310196
3984128158
200
Start Page: 100
4139464320
4148663364
4104817260
4134133134
4159842193
4156854963
4053481308
4149166948
4106268951
4124998190
200
Start Page: 110
4122310196
3984128158
4013293501
4143841303
4103604925
4137762677
4149922749
4119496830
4140182767
4152267760
200
Start Page: 120
4151774749
4119018810
4113542780
4153001474
3946072710
4013745719
4080031928
4051417235
3946070927
4154056765
200
Start Page: 130
4122149815
4131911657
4151866571
200
Start Page: 140
no more jobs found, breaking...

In [97]:
job_list = []
for job_id in id_list:
    job_post = {}
    job_url = f"https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/{job_id}"
    job_response = requests.get(job_url)
    print(job_response.status_code)
    job_soup = BeautifulSoup(job_response.text, 'html.parser')
    job_post['job_id'] = job_id
    try:
        job_post['job_title'] = job_soup.find('h2', {'class': 'top-card-layout__title font-sans text-lg papabear:text-xl font-bold leading-open text-color-text mb-0 topcard__title'}).text.strip()
    except:
        job_post['job_title'] = None

    try:
        job_post['company_name'] = job_soup.find('a', {'class': 'topcard__org-name-link topcard__flavor--black-link'}).text.strip()
    except:
        job_post['company_name'] = None

    try:
        job_post['location'] = job_soup.find('span', {'class': 'topcard__flavor topcard__flavor--bullet'}).text.strip()
    except:
        job_post['location'] = None

    try:
        job_post['time_posted'] = job_soup.find('span', {'class': 'posted-time-ago__text posted-time-ago__text--new topcard__flavor--metadata'}).text.strip()
    except AttributeError:
        try:
            job_post['time_posted'] = job_soup.find('span', {'class': 'posted-time-ago__text topcard__flavor--metadata'}).text.strip()
        except:
            job_post['time_posted'] = None

    try:
        job_post['num_applicants'] = job_soup.find('figcaption', {'class': 'num-applicants__caption'}).text.strip()
    except AttributeError:
        try:
            job_post['num_applicants'] = job_soup.find('span', {'class': 'num-applicants__caption topcard__flavor--metadata topcard__flavor--bullet'}).text.strip()
        except:
            job_post['num_applicants'] = None    
        
    job_list.append(job_post)
    delay = random.uniform(1, 3)
    time.sleep(delay)

200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
400
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200

In [98]:
jobs_df = pd.DataFrame(job_list)
jobs_df.drop_duplicates(inplace=True)
jobs_df.reset_index(inplace=True)
jobs_df

,index,job_id,job_title,company_name,location,time_posted,num_applicants
0,0,4157845565,Data Science Intern,Medcan,"Toronto, Ontario, Canada",2 days ago,Over 200 applicants
1,1,4158928976,Junior Front End Developer,Diaryz,"Toronto, Ontario, Canada",1 day ago,Over 200 applicants
2,2,4119528432,Machine Learning - Master's level Internship,Vosyn,"Etobicoke, Ontario, Canada",1 month ago,187 applicants
3,3,4151697992,Data Analyst Intern (Master's Degree),Stripe,"Toronto, Ontario, Canada",6 days ago,Over 200 applicants
4,4,4152020457,"Associate Consulting Data Scientist, Summer 2025",Klick,"Toronto, Ontario, Canada",6 days ago,Over 200 applicants
...,...,...,...,...,...,...,...
111,128,3946070927,Post-Doctoral Fellow (SRI) - TMS and MRI Study...,Sunnybrook,"Toronto, Ontario, Canada",8 months ago,Be among the first 25 applicants
112,129,4154056765,Postdoctoral Fellow - Wildlife Ecology,UNSW,"Toronto, Ontario, Canada",1 day ago,Be among the first 25 applicants
113,130,4122149815,Postdoctoral Researcher (Computational Immunol...,UNSW,"Toronto, Ontario, Canada",2 weeks ago,Be among the first 25 applicants
114,131,4131911657,Indigenous Relations Student (Mississauga),Bird Construction,"Mississauga, Ontario, Canada",5 days ago,Be among the first 25 applicants
115,132,4151866571,Postdoctoral Fellow - Computational Chemistry,UNSW,"Toronto, Ontario, Canada",1 week ago,Be among the first 25 applicants